# Generated by Django 4.2.20 on 2025-04-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_category_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producat_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('product_image', models.ImageField(upload_to='photos/product/')),
                ('price', models.IntegerField()),
                ('is_availabe', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
