# Generated by Django 4.2.20 on 2025-04-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('category_image', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
